// <auto-generated />
using System;
using GeiRanking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeiRanking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003150735_AddAdminUsers")]
    partial class AddAdminUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeiRanking.Domain.Admin.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("GeiRanking.Domain.Matches.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengedId")
                        .HasColumnType("integer")
                        .HasColumnName("challenged_id");

                    b.Property<int?>("ChallengedPositionAfter")
                        .HasColumnType("integer")
                        .HasColumnName("challenged_position_after");

                    b.Property<int?>("ChallengedPositionBefore")
                        .HasColumnType("integer")
                        .HasColumnName("challenged_position_before");

                    b.Property<int>("ChallengerId")
                        .HasColumnType("integer")
                        .HasColumnName("challenger_id");

                    b.Property<int?>("ChallengerPositionAfter")
                        .HasColumnType("integer")
                        .HasColumnName("challenger_position_after");

                    b.Property<int?>("ChallengerPositionBefore")
                        .HasColumnType("integer")
                        .HasColumnName("challenger_position_before");

                    b.Property<string>("Completion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("completion");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MovementText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("movement_text");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Warning")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("warning");

                    b.Property<int>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("ChallengedId")
                        .HasDatabaseName("ix_matches_challenged_id");

                    b.HasIndex("ChallengerId")
                        .HasDatabaseName("ix_matches_challenger_id");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("ix_matches_played_at");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_matches_winner_id");

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_matches_distinct_players", "challenger_id <> challenged_id");

                            t.HasCheckConstraint("ck_matches_winner_is_a_player", "winner_id IN (challenger_id, challenged_id)");
                        });
                });

            modelBuilder.Entity("GeiRanking.Domain.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Backhand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("backhand");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Hand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hand");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Nickname")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nickname");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("photo_path");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.RankingHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int?>("FromPosition")
                        .HasColumnType("integer")
                        .HasColumnName("from_position");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int?>("ToPosition")
                        .HasColumnType("integer")
                        .HasColumnName("to_position");

                    b.HasKey("Id")
                        .HasName("pk_ranking_history");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_ranking_history_event_id");

                    b.HasIndex("PlayerId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_ranking_history_player_id_occurred_at_id");

                    b.ToTable("ranking_history", (string)null);
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.RankingSnapshotEntry", b =>
                {
                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Position")
                        .HasName("pk_ranking_snapshot");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_ranking_snapshot_player_id");

                    b.ToTable("ranking_snapshot", (string)null);
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.StoredRankingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<int[]>("InitialOrder")
                        .HasColumnType("integer[]")
                        .HasColumnName("initial_order");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_ranking_events");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_ranking_events_match_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_ranking_events_player_id");

                    b.HasIndex("OccurredAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_ranking_events_occurred_at_created_at_id");

                    b.ToTable("ranking_events", (string)null);
                });

            modelBuilder.Entity("GeiRanking.Domain.Matches.Match", b =>
                {
                    b.HasOne("GeiRanking.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("ChallengedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_players_challenged_id");

                    b.HasOne("GeiRanking.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("ChallengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_players_challenger_id");

                    b.HasOne("GeiRanking.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_players_winner_id");
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.RankingHistoryEntry", b =>
                {
                    b.HasOne("GeiRanking.Infrastructure.Persistence.StoredRankingEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranking_history_ranking_events_event_id");

                    b.HasOne("GeiRanking.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ranking_history_players_player_id");
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.RankingSnapshotEntry", b =>
                {
                    b.HasOne("GeiRanking.Domain.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ranking_snapshot_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeiRanking.Infrastructure.Persistence.StoredRankingEvent", b =>
                {
                    b.HasOne("GeiRanking.Domain.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ranking_events_matches_match_id");

                    b.HasOne("GeiRanking.Domain.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ranking_events_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
