<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeiRanking.Infrastructure\GeiRanking.Infrastructure.csproj" />
  </ItemGroup>
</Project>